# Generated by Django 3.0.7 on 2022-02-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20220217_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='portfolio.Customer'),
        ),
    ]
